#######
# Compiled from data/cam/functions/load.mcscript
# to .//data/cam/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function cam:mcscript/load
# do not remove this line!!
tellraw @a[tag=!camNoText,gamemode=creative] [{"text":"[Cam] ", "color":"gold"},{"text":"Camera package successfully installed and initialized","color":"green"}]
scoreboard objectives add camPage dummy

scoreboard players set 20 camPos 2
scoreboard players set 10 camPos 10
scoreboard players set -1 camPos -1
execute as @a unless score @s camTime matches 1.. run scoreboard players set @s camTime 1


