#######
# Compiled from data/cam/functions/main.mcscript
# to .//data/cam/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function cam:tool
execute as @e[tag=cam1] at @s run particle minecraft:dust 0.4 0.4 0.4 0.4 ~ ~ ~ 0 0.5 0 1 50 normal @a[gamemode=creative,tag=!camNoParticles,tag=!camRunning]
execute as @e[tag=cam2] at @s run particle minecraft:dust 0.4 0.4 0.4 0.4 ~ ~ ~ 0 0.5 0 1 50 normal @a[gamemode=creative,tag=!camNoParticles,tag=!camRunning]
execute as @e[tag=camParticle] at @s if entity @e[tag=cam1] if entity @e[tag=cam2] run function cam:particles
execute as @a[tag=camRunning,tag=!camNotFixed] at @s run execute if score camTime camTime matches 1.. run scoreboard players remove camTime camTime 1
execute as @a[tag=camRunning,tag=!camNotFixed] at @s run execute if score camTime camTime matches 1.. run execute as @e[tag=camRunner] at @s run function cam:calc/tpx
execute as @a[tag=camRunning,tag=!camNotFixed] at @s run execute if score camTime camTime matches 1.. run execute as @e[tag=camRunner] at @s run function cam:calc/tpy
execute as @a[tag=camRunning,tag=!camNotFixed] at @s run execute if score camTime camTime matches 1.. run execute as @e[tag=camRunner] at @s run function cam:calc/tpz
execute as @a[tag=camRunning,tag=!camNotFixed] at @s run execute if score camTime camTime matches 1.. run execute if entity @s[tag=!camNoRot] as @e[tag=camRunner] at @s run function cam:calc/tpr
execute as @a[tag=camRunning,tag=!camNotFixed] at @s run execute if score camTime camTime matches 1.. run execute if entity @s[tag=!camNoRot] as @e[tag=camRunner] at @s run function cam:calc/tpr2
execute as @a[tag=camRunning,tag=!camNotFixed] at @s run execute if score camTime camTime matches 1.. run tp @s @e[tag=camRunner,limit=1,sort=nearest]
execute as @a[tag=camRunning,tag=!camNotFixed] at @s run execute if score camTime camTime matches 0 run function cam:stop
execute as @a[tag=camRunning,tag=camNotFixed] at @s run execute if score camTime camTime matches 1.. run scoreboard players remove camTime camTime 1
execute as @a[tag=camRunning,tag=camNotFixed] at @s run execute if score camTime camTime matches 1.. run function cam:calc/tpx
execute as @a[tag=camRunning,tag=camNotFixed] at @s run execute if score camTime camTime matches 1.. run function cam:calc/tpy
execute as @a[tag=camRunning,tag=camNotFixed] at @s run execute if score camTime camTime matches 1.. run function cam:calc/tpz
execute as @a[tag=camRunning,tag=camNotFixed] at @s run execute if score camTime camTime matches 1.. run execute if entity @s[tag=!camNoRot] run function cam:calc/tpr
execute as @a[tag=camRunning,tag=camNotFixed] at @s run execute if score camTime camTime matches 1.. run execute if entity @s[tag=!camNoRot] run function cam:calc/tpr2
execute as @a[tag=camRunning,tag=camNotFixed] at @s run execute if score camTime camTime matches 0 run function cam:stop
tag @e[tag=camOnStop,tag=camOnStop2] remove camOnStop
tag @e[tag=camOnStop2] remove camOnStop2
tag @e[tag=camOnStop] add camOnStop2