#######
# Compiled from data/cam/functions/poses.mcscript
# to .//data/cam/functions/pos1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @e[tag=cam1]
kill @e[tag=camParticle]
summon armor_stand ~ ~100 ~ {CustomName:"{\"text\":\"Position 1\"}", Tags: [camPos,cam1],Invisible:1,Marker:1,NoGravity:1,CustomNameVisible:1}
tp @e[tag=cam1] ~ ~ ~ facing ^ ^ ^1
execute store result score camX1 camPos run data get entity @e[tag=cam1,sort=nearest,limit=1] Pos[0] 100
execute store result score camY1 camPos run data get entity @e[tag=cam1,sort=nearest,limit=1] Pos[1] 100
execute store result score camZ1 camPos run data get entity @e[tag=cam1,sort=nearest,limit=1] Pos[2] 100
execute store result score camRv1 camPos run data get entity @e[tag=cam1,sort=nearest,limit=1] Rotation[0] 10
execute store result score camR1 camPos run data get entity @e[tag=cam1,sort=nearest,limit=1] Rotation[1] 10
summon area_effect_cloud ~ ~ ~ {Duration: 2147483647, Tags: [camPos,camParticle]}
execute as @e[tag=cam1] run function cam:calc/positions
