#######
# Compiled from data/cam/functions/load.mcscript
# to .//data/cam/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######

# Extended from data/cam/functions/load.mcscript
# to data/cam/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add camTime dummy
scoreboard objectives add camPos dummy
scoreboard objectives add camPosD dummy
scoreboard objectives add camGUI dummy

# Extended from data/cam/functions/tpX.mcscript
# to data/cam/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add camI dummy
