#######
# Compiled from data/cam/functions/tpX.mcscript
# to data/cam/functions/mcscript/foreach2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tp @s ~ ~ ~ ~-0.01 ~
scoreboard players remove camI camI 1
execute if entity @s[tag=!mcscriptStop] if score camI camI > camDRv camPosD rotated ~ ~ run function cam:mcscript/tpr2
tag @s[tag=mcscriptStop] remove mcscriptStop
