#######
# Compiled from data/cam/functions/tpX.mcscript
# to .//data/cam/functions/calc/tpr2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set camI camI 0
execute if score camI camI < camDR camPosD run function cam:mcscript/tpr3
scoreboard players set camI camI 0
execute if score camI camI > camDR camPosD run function cam:mcscript/tpr4