#######
# Compiled from data/cam/functions/tpX.mcscript
# to .//data/cam/functions/calc/tpx.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set camI camI 0
execute if score camI camI < camDX camPosD run function cam:mcscript/tpx1
scoreboard players set camI camI 0
execute if score camI camI > camDX camPosD run function cam:mcscript/tpx2
