#######
# Compiled from data/cam/functions/tpX.mcscript
# to .//data/cam/functions/calc/tpz.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set camI camI 0
execute if score camI camI < camDZ camPosD run function cam:mcscript/tpz1
scoreboard players set camI camI 0
execute if score camI camI > camDZ camPosD run function cam:mcscript/tpz2
