#######
# Compiled from data/exam/functions/load.mcscript
# to .//data/exam/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function exam:mcscript/load
# do not remove this line!!