#######
# Compiled from data/exam/functions/main.mcscript
# to .//data/exam/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[tag=path3,tag=camOnStop] at @s run scoreboard players set @s camTime 7
execute as @a[tag=path3,tag=camOnStop] at @s run execute positioned -423 45 1030 rotated -106 12 run function cam:pos1
execute as @a[tag=path3,tag=camOnStop] at @s run execute positioned -423 91 1030 rotated -107 33 run function cam:pos2
execute as @a[tag=path3,tag=camOnStop] at @s run tag @s add path4
execute as @a[tag=path3,tag=camOnStop] at @s run function cam:start
execute as @a[tag=path3,tag=camOnStop] at @s run tag @s remove path3
execute as @a[tag=path2,tag=camOnStop] at @s run scoreboard players set @s camTime 4
execute as @a[tag=path2,tag=camOnStop] at @s run execute positioned -445 36 1004 rotated 128 14 run function cam:pos1
execute as @a[tag=path2,tag=camOnStop] at @s run execute positioned -436 36 995 rotated -166 10 run function cam:pos2
execute as @a[tag=path2,tag=camOnStop] at @s run tag @s add path3
execute as @a[tag=path2,tag=camOnStop] at @s run function cam:start
execute as @a[tag=path2,tag=camOnStop] at @s run tag @s remove path2
execute as @a[tag=path1,tag=camOnStop] at @s run scoreboard players set @s camTime 8
execute as @a[tag=path1,tag=camOnStop] at @s run execute positioned -369 50 1126 rotated 144 12 run function cam:pos1
execute as @a[tag=path1,tag=camOnStop] at @s run execute positioned -421 43 1059 rotated 140 19 run function cam:pos2
execute as @a[tag=path1,tag=camOnStop] at @s run tag @s add path2
execute as @a[tag=path1,tag=camOnStop] at @s run function cam:start
execute as @a[tag=path1,tag=camOnStop] at @s run tag @s remove path1
